$schema: "https://github.com/Klyro-DNS/Klyro/releases/download/1.0.2/zone.schema.json"
name: example.com
type: primary
enabled: true
records:
  - name: "@"
    type: A
    ttl: 3600
    value: "192.168.1.10"

  - name: "www"
    type: A
    ttl: 3600
    value: "192.168.1.10"

  - name: "api"
    type: A
    ttl: 300
    value: "192.168.1.20"

  - name: "@"
    type: MX
    ttl: 3600
    priority: 10
    value: "mail.example.com"

  - name: "blog"
    type: CNAME
    ttl: 3600
    value: "www.example.com"
