$schema: "https://github.com/Klyro-DNS/Klyro/releases/download/1.0.2/zone.schema.json"
name: home.local
type: primary
enabled: true
records:
  - name: "@"
    type: A
    ttl: 300
    value: "192.168.1.1"

  - name: "nas"
    type: A
    ttl: 300
    value: "192.168.1.100"

  - name: "printer"
    type: A
    ttl: 300
    value: "192.168.1.200"
