$schema: "../../zone.schema.json"
name: home.local
type: primary
enabled: true
records:
    - name: nas
      type: A
      ttl: 300
      value: 192.168.1.100
    - name: printer
      type: A
      ttl: 300
      value: 192.168.1.200
    - name: test
      type: A
      ttl: 3600
      value: 192.168.1.10
